name: CI Workflow

on:
  push:
    branches:
      - 'feature/*'
      - 'dev'
      - 'release-*'
      - 'hotfix-*'
      - 'main'
  pull_request:
    branches:
      - 'dev'
      - 'release-*'
      - 'hotfix-*'

jobs:
  build:
    name: Setup resources
    runs-on: ubuntu-24.04
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage

      - name: Run UT and report coverage
        run: |
          coverage run -m unittest tests/test*
          coverage xml

      - name: Upload the coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

  DependencyCheck:
    uses: ./.github/workflows/dependency-check.yml

  SonarScanner:
    needs: build
    uses: ./.github/workflows/sonarcloud.yml
    secrets: inherit

  BuildScanPushImage:
    needs: [build, DependencyCheck, SonarScanner]
    uses: ./.github/workflows/trivy.yml
    secrets: inherit




