name: SonarScanner Workflow

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact for coverage
        uses: actions/download-artifact@v4
        with:
          name: coverage-report

      - name: Display structure of downloaded files
        run: ls -R
