name: SonarScanner Workflow

on:
  workflow_run:
    workflows: ["CI Workflow"]
    types:
      - completed

jobs:
  build:
    - name: Download artifact for coverage
      id:
      uses: actions/download-artifact@v4
      with:
        name: coverage-report
    - name: Display structure of downloaded files
      run: ls -R