name: SonarScanner Workflow

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact for coverage
        uses: actions/download-artifact@v4
        with:
          name: coverage-report

      - name: Code checkout
        uses: actions/checkout@v4

      - name: SonarQubeScan
        uses: SonarSource/sonarqube-scan-action@v4
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

