name: SonarScanner

on:
  push:
    branches:
      - 'feature/*'
      - 'dev'
      - 'release-*'
      - 'hotfix-*'
      - 'main'
  pull_request:
    branches:
      - 'dev'
      - 'release-*'
      - 'hotfix-*'

jobs:
  build:
    name: Pull resources
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          fetch_depth: 0
      - name: Check repo
        run: ls -la