name: Testing workflow

on:
  workflow_call:

#concurrency:
#  group: ${{ github.workflow }}-${{ github.ref }}
#  cancel-in-progress: false

jobs:
  build:
    name: Setup resources
    runs-on: ${{ vars.LINUX_RUNNER_VER }}
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install coverage

      - name: Run Unit Tests and report coverage
        run: |
          coverage run -m unittest ./${{ github.workflow }}/tests/ -s tests
          coverage xml

      - name: Upload the coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ github.workflow }}
          path: coverage.xml