name: Build and scan image
on:
  workflow_call:
    secrets:
      git_token:
        required: true

jobs:
  build:
    strategy:
      matrix:
        microservice: [billing-service, subscription-service, db-service, user-service]
    name: Build and scan image
    runs-on: ${{ var.LINUX_
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/${{ github.actor }}/${{ matrix.microservice }}:${{ github.sha }} ./${{ matrix.microservice }}/

      - name: Run Trivy vulnerability scanner for microservice
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'docker.io/${{ github.actor }}/${{ matrix.microservice }}:${{ github.sha }}'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.git_token }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Push the image
        run: |
          docker push ghcr.io/${{ github.actor }}/${{ matrix.microservice }}:latest